# Funding / sponsor button for this repository.
# Uncomment and set the lines for the platforms you use.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [the-dev-center]
# patreon:
# open_collective:
# ko_fi:
# liberapay:
# custom: ["https://example.com/donate"]
